backend:
  name: git-gateway
  repo: plesioo/SFW-Website
  branch: master
  identity_url: https://auth.decapbridge.com/sites/8cb8b33a-17dd-4625-8f2b-5dd7c28c7849
  gateway_url: https://gateway.decapbridge.com

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

locale: de

# Add site links in DecapCMS (optional)
site_url: https://sfw-website.netlify.app
media_folder: static/img
public_folder: /img
collections:
  - name: "workshop"
    label: "Workshops"
    label_singular: "Workshop"
    folder: "content/workshop"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "workshop/{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }

      - label: "Veröffentlichungsdatum"
        name: "date"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        time_format: "HH:mm:ssZ"
        default: "{{now}}"

      - label: "Bild"
        name: "image"
        widget: "image"

      - label: "Inhalt"
        name: "body"
        widget: "markdown"
        modes: ["rich_text"]

  - name: "course"
    label: "Wahlkurse"
    label_singular: "Wahlkurs"
    folder: "content/course"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "course/{{slug}}"
    fields:
      - label: "Kursinformationen"
        name: "courseInfo"
        widget: "object"
        fields:
          - label: "Anrede Leitung"
            name: "leadSalutation"
            widget: "select"
            options: ["Herr", "Frau"]

          - { label: "Nachname Leitung", name: "leadName", widget: "string" }

          - label: "Jahrgangsstufen"
            name: "grades"
            widget: "string"
            hint: "z.B. 5-12"

          - { label: "Raum", name: "room", widget: "string" }

          - label: "Wochentage"
            name: "weekdays"
            widget: "select"
            options: ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag"]
            multiple: true

          - label: "Uhrzeit"
            name: "time"
            widget: "string"
            hint: "z.B. 10:00-12:00"

      - label: "Artikelinformationen"
        name: "articleInfo"
        widget: "object"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - label: "Veröffentlichungsdatum"
            name: "date"
            widget: "datetime"
            date_format: "YYYY-MM-DD"
            time_format: "HH:mm:ssZ"
            default: "{{now}}"

          - { label: "Bild", name: "image", widget: "image" }
          - label: "Inhalt"
            name: "body"
            widget: "markdown"
            modes: ["rich_text"]
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    i18n: true
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - {
          label: "Veröffentlichungsdatum",
          name: "date",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm:ssZ",
        }
      - { label: "Beschreibung", name: "description", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
