backend:
  name: git-gateway
  repo: plesioo/SFW-Website
  branch: master
  identity_url: https://auth.decapbridge.com/sites/8cb8b33a-17dd-4625-8f2b-5dd7c28c7849
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}}
    update: Update {{collection}} “{{slug}}” - {{author-name}}
    delete: Delete {{collection}} “{{slug}}” - {{author-name}}
    uploadMedia: Upload “{{path}}” - {{author-name}}
    deleteMedia: Delete “{{path}}” - {{author-name}}
    openAuthoring: Message {{message}} - {{author-name}}

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

locale: de

# Add site links in DecapCMS (optional)
site_url: https://sfw-website.netlify.app
media_folder: static/img
public_folder: /img
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    i18n: true
    editor:
      preview: false
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - {
          label: "Veröffentlichungsdatum",
          name: "date",
          widget: "datetime",
          date_format: "YYYY-MM-DD",
          time_format: "HH:mm:ssZ",
        }
      - { label: "Beschreibung", name: "description", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
